### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by milanffm** [Froelund/strapi-plugin-images#1]
hi,
nice plugin :-)
I get an error after install the plugin 
` error Cannot read property 'services' of undefined`
`/strapi-plugin-images-master/middlewares/images/index.js:6:52`

any idea?

**Comment by milanffm** [comment]
strapi version: 3.0.0-alpha.14.3

**Comment by milanffm** [comment]
I fixed it. I have to rename the Plugin to "images".
:-)

**Comment by Froelund** [comment]
Thanks for the report!
I should actually take care of the issue in the code.

**Comment by Froelund** [comment]
@milanffm When you install the plugin, the folder will be called `strapi-plugin-images` right?

**Comment by milanffm** [comment]
I'm new in strapi how do I install it correctly? I copy the code to the plugin folder and than edit the /admin/build/config/plugin.json .

**Comment by milanffm** [comment]
I can't get it work. how could I install the plugin correctly?
`strapi install strapi-plugin-images`
doesn't work, because it is not an npm module..

**Comment by Froelund** [comment]
That is wierd. The plugin is published to npmjs.com, however when I'm running `strapi install images` the error is this:
```
[2018-10-22T17:39:57.182Z] debug Installation in progress...
[2018-10-22T17:39:57.183Z] debug Installing the plugin from npm registry.
[2018-10-22T17:39:59.182Z] error An error occurred during plugin installation.
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-images
```
But when you follow the url, you'll go to the plugins npm page..
I'll investigate.

**Comment by Froelund** [comment]
I found the issue. The issue is that the strapi-install script tries to install the plugin in the same version as your project strapi version.
https://github.com/strapi/strapi/blob/master/packages/strapi/bin/strapi-install.js#L72

**Comment by Froelund** [comment]
@milanffm I've just added steps to install this plugin manually.
Would you please test them?

```
npm install strapi-plugin-images --no-save
mv node_modules/strapi-plugin-images plugins/images
cp node_modules/strapi/node_modules/strapi-generate-plugin/templates/gitignore plugins/images/.gitignore
```

**Comment by milanffm** [comment]
installation works. But I get an blank screen on the plugin page. 
![bildschirmfoto 2018-10-23 um 10 44 15](https://user-images.githubusercontent.com/16035756/47347968-b7bcec00-d6b0-11e8-9f0a-5aa7386ab085.png)
can I use the file upload plugin?

**Comment by milanffm** [comment]
ok it works THNX, I had to set the `get` method to Public 
![bildschirmfoto 2018-10-23 um 10 54 20](https://user-images.githubusercontent.com/16035756/47348606-20589880-d6b2-11e8-9527-f9a7559b8fee.png)

**Comment by Froelund** [comment]
Great! Thanks for testing!
