### ISSUE TITLE
cache or save images

### ISSUE THREAD

**Issue by merijnponzo** [Froelund/strapi-plugin-images#2]
thanks for this plugin !
Is it possible to actually cache or save the resized images, or does it always work 'on the fly' ?

Gives me succesfully a small image
http://localhost:1337/images/5c27c3c4d9195d07358a1b3c?size=120x120

But I excepected to see a generated version within the strapi admin -> images

thanks

**Comment by Froelund** [comment]
Hi @merijnvanessen, and thanks for your feedback. I'm testing a new version of the plugin, and will publish it soon.

**Comment by adamkhan** [comment]
Absolutely! I know you say not for production, but, well, for a low-traffic site that I'm eager to get online, I believe I will be using it. And hitting the server each time for a resize, oh dear...

**Comment by Froelund** [comment]
@merijnvanessen @adamkhan I have just pushed a new branch with optimized image processing and caching of images: `feature/processing_worker` Check it out if you'd like :)

**Comment by adamkhan** [comment]
Great stuff, @Froelund! I ended up going with a 3rd-party solution (Cloudinary), which I was loathe to do but seems to be working out fine so far. Next project I'll try again to do it internally with your plugin.

**Comment by Froelund** [comment]
That sounds like a really good idea.
I imagine that Cloudinary would be way better at processing images ;)

**Comment by Froelund** [comment]
I am working on getting the new branch `feature/processing_worker` more stable, and publish a new version of this plugin with this setup. Down sides is that the plugin now relies on Redis - but I consider the value more significant.
I will close this issue, and release the new version.
