### ISSUE TITLE
Some notes from trying the plugin

### ISSUE THREAD

**Issue by adamkhan** [Froelund/strapi-plugin-images#4]
Note that the _id is not the hash that Strapi uses to display the images itself, but another field.

Also, the plugin requires both width and height separated by "x". if you want to resize just along one side, use "jimp.AUTO" so "size=1000xjimp.AUTO" for auto height (though this seems to not work if the size difference is too different from the original).

Great job, @Froelund, this is the first 3rd-party Strapi plugin I've used, and I've been waiting months for someone with more understanding than I to do it!

**Comment by adamkhan** [comment]
OK I was using the wrong variable, the public id, not the _id! Not sure how we see the _id from within Strapi but I can call it via GraphQL, which is how I need it. Great stuff!

**Comment by adamkhan** [comment]
Huh, well now I'm getting:

~~~

TypeError: ctx.internalServerError is not a function
    at get (/Users/adamkhan/Sites/[BLAH BLAH]/plugins/images/controllers/Images.js:41:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-02-14T14:40:04.919Z] debug GET /images/5c58214da9f0d52cf5cfa2e6?size=300 (2857 ms)
~~~

**Comment by adamkhan** [comment]
Well it turns out I was presuming it was possible to define just one side, ie, ?size=300 and presume that's width, but the plugin requires both width and height, ie, ?size=300x200 and doesn't work with "auto" as a value. Looking at the Jimp docs at https://github.com/oliver-moran/jimp, the I'm trying to see how we can resize by just one side.

**Comment by Froelund** [comment]
Great feedback @adamkhan! Good idea regarding keeping one of the dimensions optional 👍
Could you elaborate on your point about the `_id` and hash?

**Comment by Froelund** [comment]
Again - Thanks for the feedback. I will make width and height optional.
I've taken your points regarding using the `hash` rather than `_id` into consideration.
